ACL checks are not sufficient for checking access.  Access is falsely denied when bucket policy is used.
carlspring/s3fs-nio pull request #133
Opened 2020-12-10 13:58 UTC by electricsam

# Pull Request Description

Using ACLs to check for object access is not sufficient.  The bucket policy can override the ACL.  This can be a problem when accessing a public bucket in a different account where ACLs are not configured.   In general, AWS recommends using bucket policies over ACLs.  

These changes remove the ACL check and simply check if object exists for the given user.  If that user cannot read or write to that object, an error will happen at the time of that action.

# Acceptance Test

* [x] Building the code with `mvn clean install -Pintegration-tests` still works.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see [provide details here]
  * [x] No

2020-12-10 16:08 UTC, carlspring commented
Hi @electricsam ,

Thank you for your contribution!

Would you mind signing the [ICLA](https://5fbab373a589ce000892cbd9--s3fs-nio.netlify.app/assets/resources/pdfs/ICLA.pdf), as described in the [Legal](https://s3fs-nio.carlspring.org/contributing/legal/) section of our wiki?

Also, please, feel free to join our [chat channel](https://chat.carlspring.org/channel/s3fs-nio-community), if you'd like to learn more about the project and/or like to find out what else you could help with.

Kind regards,

Martin

2020-12-10 16:10 UTC, carlspring commented
@ptirador , @elerch, @markjschreiber, @pditommaso ,

Could you please review this? :)

2020-12-10 16:47 UTC, electricsam commented
Hi Martin,

I filled out the ICLA and sent it to carlspring@gmail.com<mailto:carlspring@gmail.com>.

Cheers,

Chris


Chris Slater
Lead Software Engineer
Cooperative Institute for Research in Environmental Sciences (CIRES) at
University of Colorado Boulder and
NOAA National Centers for Environmental Information
325 Broadway, NOAA E/GC3
Boulder, Colorado 80305-3337

E-mail: christopher.r.slater@colorado.edu<mailto:christopher.r.slater@colorado.edu>
Office: 1B605, NOAA David Skaggs Research Center

On Dec 10, 2020, at 9:08 AM, Martin Todorov <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi @electricsam<https://github.com/electricsam> ,

Thank you for your contribution!

Would you mind signing the ICLA<https://5fbab373a589ce000892cbd9--s3fs-nio.netlify.app/assets/resources/pdfs/ICLA.pdf>, as described in the Legal<https://s3fs-nio.carlspring.org/contributing/legal/> section of our wiki?

Also, please, feel free to join our chat channel<https://chat.carlspring.org/channel/s3fs-nio-community>, if you'd like to learn more about the project and/or like to find out what else you could help with.

Kind regards,

Martin

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/carlspring/s3fs-nio/pull/133#issuecomment-742617656>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABN2AKPL6KGLKG65VBHBNE3SUDXBLANCNFSM4UVBZVFA>.

2020-12-10 16:56 UTC, carlspring commented
Thanks a lot, @electricsam ! I can confirm I have received it. )

2020-12-10 18:31 UTC, carlspring commented on src/main/java/org/carlspring/cloud/storage/s3fs/S3AccessControlList.java
> +    @Deprecated
Thanks for adding some documentation here! :)

2020-12-10 18:32 UTC, carlspring commented on src/main/java/org/carlspring/cloud/storage/s3fs/S3AccessControlList.java
> +    )
```suggestion
                               )
```

2020-12-10 18:33 UTC, carlspring commented on src/main/java/org/carlspring/cloud/storage/s3fs/S3AccessControlList.java
> +    )
```suggestion
                               )
```

2020-12-10 18:33 UTC, carlspring commented on src/main/java/org/carlspring/cloud/storage/s3fs/S3AccessControlList.java
> +            // Any permission problems will have to be handled at time of access.
Thanks for adding these clarifications! :)

2020-12-10 18:34 UTC, carlspring commented on src/main/java/org/carlspring/cloud/storage/s3fs/S3FileSystemProvider.java
>          }
:+1:

2020-12-10 18:35 UTC, carlspring commented on src/main/java/org/carlspring/cloud/storage/s3fs/S3FileSystemProvider.java
> +    }
```suggestion
    private static boolean isBucketRoot(S3Path s3Path)
    {
        String key = s3Path.getKey();
        return key.equals("") || key.equals("/");
    }
```

2020-12-10 18:36 UTC, carlspring commented on src/main/java/org/carlspring/cloud/storage/s3fs/S3FileSystemProvider.java
> +        }
Cosmetic: Just braces on new lines, please.
```suggestion
        if(isBucketRoot(s3Path))
        {
            // check to see if bucket exists
            try
            {
                s3Utils.listS3Objects(s3Path);
                return true;
            }
            catch (SdkException e)
            {
                return false;
            }
        }
```

2020-12-10 18:37 UTC, carlspring commented on src/main/java/org/carlspring/cloud/storage/s3fs/util/S3Utils.java
> +            .build();
Cosmetic: Just code styke changes.
```suggestion
        final ListObjectsV2Request request = ListObjectsV2Request.builder()
                                                                 .bucket(bucketName)
                                                                 .prefix(keyFolder)
                                                                 .maxKeys(1)
                                                                 .build();
```

2020-12-10 20:13 UTC, carlspring requested changes
@electricsam ,

Thanks for this pull request! Would you mind applying the cosmetic code style changes I have raised?

Many thanks in advance! :)

2020-12-11 16:43 UTC, ptirador requested changes
HI @electricsam,

Thanks for this pull request! Would you mind applying the changes that I requested?
Apart from these, LGTM!

CC @carlspring

2020-12-11 16:43 UTC, ptirador commented on src/test/java/org/carlspring/cloud/storage/s3fs/fileSystemProvider/CheckAccessTest.java
> +            () -> s3fsProvider.checkAccess(file1, AccessMode.WRITE));
Cosmetic: code style change.

```suggestion
        final Exception exception = assertThrows(NoSuchFileException.class,
                                                 () -> s3fsProvider.checkAccess(file1, AccessMode.WRITE));
```

2020-12-11 16:43 UTC, ptirador commented on src/main/java/org/carlspring/cloud/storage/s3fs/S3AccessControlList.java
>                      throw new AccessDeniedException(fileName(), null, "file is not executable");
`switch` statement has one case label only, and should probably be replaced with an `if` statement.

```suggestion
            if (accessMode == AccessMode.EXECUTE)
            {
                throw new AccessDeniedException(fileName(), null, "file is not executable");
            }
```

2020-12-12 12:57 UTC, carlspring commented on src/main/java/org/carlspring/cloud/storage/s3fs/S3AccessControlList.java
> +    )
```suggestion
                               final Owner owner //unused, but keeping to preserve signature
                               )
```

2020-12-12 12:59 UTC, carlspring commented on src/main/java/org/carlspring/cloud/storage/s3fs/S3AccessControlList.java
> +            }
```suggestion
```

2020-12-12 13:04 UTC, carlspring commented on src/test/java/org/carlspring/cloud/storage/s3fs/fileSystemProvider/CheckAccessTest.java
> +        throws IOException
```suggestion
            throws IOException
```

2020-12-12 13:05 UTC, carlspring commented on src/main/java/org/carlspring/cloud/storage/s3fs/util/S3Utils.java
> +
```suggestion
```

2020-12-12 13:06 UTC, carlspring approved these changes
LGTM! :)

2020-12-12 13:08 UTC, merged